### ISSUE TITLE
Remove mentions of polyfill.io

### ISSUE THREAD

**Issue by Daeloth** [pixijs/pixijs.com#112]
**Links to the mentions:**
https://github.com/pixijs/pixijs.com/blob/a08bd3dc4f018746b32877f3fe05903f020e610f/docs/guides/migrations/v7.md?plain=1#L11
https://github.com/pixijs/pixijs.com/blob/a08bd3dc4f018746b32877f3fe05903f020e610f/versioned_docs/version-7.x/guides/migrations/v7.md?plain=1#L11

**Information on polyfill.io:**
https://x.com/triblondon/status/1761852117579427975
https://github.com/polyfillpolyfill/polyfill-service/issues/2873

Polyfill.io shouldn't be linked to, the domain has been compromised and now links to chinese scams/malware

**Comment by Zyie** [comment]
thanks for raising this, the links have now been removed!
