### ISSUE TITLE
Doc links within tutorials are prevented from being redirected with plugin-client-redirects

### ISSUE THREAD

**Issue by momer** [pixijs/pixijs.com#133]
**Description:**

Within tutorials, like the [8.x Choo Choo Train](https://pixijs.com/8.x/tutorials/choo-choo-train#1) tutorial, links to guides, examples, etc. like the [Getting Started](https://pixijs.com/guides/basics/getting-started#loading-pixijs) link on the Choo Choo tutorial are prevented from being redirected to their correctly prefixed route by an event listener.

Clicking on the link mentioned above _should_ make use of the [docusaurus/plugin-client-redirects](https://github.com/pixijs/pixijs.com/blob/main/docusaurus.config.js#L80-L101) configuration, but, instead, we get a `404`-type page. 

However, if - **in another tab** - you copy/paste the URL from that link (that is, `https://pixijs.com/guides/basics/getting-started#loading-pixijs`) into your browser address bar, you _will_ be redirected to the correct page, located at `https://pixijs.com/8.x/guides/basics/getting-started#loading-pixijs`.

**Analysis:**

Some light diving into the situation shows that there are a few event `click` event listeners on the link, thanks to Chrome's [Performance timeline](https://medium.com/hackernoon/finding-that-pesky-listener-thats-hijacking-your-event-javascript-b590593f2a83).

> Note: this is from a build running on my machine, via `npm run build` and `npm run serve`

![Image](https://github.com/user-attachments/assets/5a81818b-b468-4a30-8a50-4cf952a9e317)

It turns out, that by deleting the first event listener, which I think has to do with the React Router, the link event _isn't_ hijacked, and the redirection from docusaurus' configuration works as expected.

**Resolution:**

Options:

1. I'm not quite sure how to prevent the behavior of the React Router in this case. But, if someone does know how, that would be the ideal way to resolve this!

2. Otherwise, rather than using root-based links to guides, etc. (that is, links like `/guides/components/containers`), links within tutorials, they should instead be prefixed with the correct version-prefix of the actual guide location. 
   - This is a bit more manual and error-prone, but might be the way forward!

**Comment by Zyie** [comment]
fixed in #138
