### ISSUE TITLE
AssetPack link goes to a fork instead of pixijs' repository

### ISSUE THREAD

**Issue by adngdb** [pixijs/pixijs.com#34]
Hey folks,

I'm surprised to see that the link, in the Ecosystem dropdown, to AssetPack goes to a fork of the pixijs repo — https://github.com/ehtick/pixijs-assetpack — instead of your own repo. Both seem to have the same history. I don't know who our fellow ehtick is, but seeing his 2.2k repositories does not make me trusty. 

Apologies if there's a good reason for this, but from a new comer's perspective, this seem like it might be a security issue. :-)

**Comment by Zyie** [comment]
Hey, thanks for spotting this

Must have been an autocomplete error that we didn't spot. Should be once the ci finishes
