### ISSUE TITLE
Bug: RenderTexture Container does not render / behavior for v6 is different to v7

### ISSUE THREAD

**Issue by cvissie** [pixijs/pixijs.com#38]
### Current Behavior

It would seem that RenderTexture no longer renders a container correctly from v7 onwards.

https://pixijs.com/playground?exampleId=textures.renderTextureBasic

![image](https://github.com/pixijs/pixijs/assets/571532/707d74c6-6c23-44d0-ad30-ba787b7b708d)

### Expected Behavior

In v6 this used to render correctly.

https://pixijs.com/playground?exampleId=textures.renderTextureBasic&pixiVersion=6.5.10

![image](https://github.com/pixijs/pixijs/assets/571532/604d0afa-92f9-4f28-87d4-8c0ece9efaa2)

### Steps to Reproduce

https://pixijs.com/playground?exampleId=textures.renderTextureBasic

### Environment

- **`pixi.js` version**: *e.g. 7.1.0*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. Ubuntu 22.04*
- **Running Example**: *e.g. <https://pixiplayground.com/>*

**Comment by bigtimebuddy** [comment]
The syntax needs to be updated:
```js
const rt = PIXI.RenderTexture.create({
    width: 300,
    height: 300,
    scaleMode: PIXI.SCALE_MODES.LINEAR,
    resolution: 1,
});
```
```js
app.renderer.render(container, { renderTexture: rt });
```

**Comment by cvissie** [comment]
And here was me being hopeful the issue is on PIXI side 😄 It would seem the real issue is on my side.  Thanks for fixing the example!
