### ISSUE TITLE
Placeholder text in the tutorial's meta tag

### ISSUE THREAD

**Issue by x-gkm** [pixijs/pixijs.com#47]
I created an issue instead of a pull request because I don't know what would be appropriate. Here's how it's currently rendered in Discord: ![image](https://github.com/pixijs/pixijs.com/assets/48455693/58703d08-f79e-4c35-ad2d-a065d0c57deb)

I think this is where that text comes from: https://github.com/pixijs/pixijs.com/blob/86f2d8694c86b7830e92fabd25c18784a2a17007/src/pages/tutorial.tsx#L8

**Comment by Zyie** [comment]
This has been resolved so closing the issue!
