### ISSUE TITLE
PixiJS Site Example redirects users

### ISSUE THREAD

**Issue by aJamDonut** [pixijs/pixijs.com#58]
Maybe a mistake but old pixi examples versions page will auto redirect you to new page ! 

http://pixijs.github.io/examples/#/plugin-projection/basic.js

old examples of previous versions should remain available !

Redirection should removed.

**Comment by Zyie** [comment]
Hey!, so there are really two issues here. 

The first is that not all v5/6 examples got ported to v7. So the `plugin-projection` example doesn't exist on the example site. It can be found on the `pixijs.io/examples-v5` site here:

https://pixijs.io/examples-v5/#/plugin-projection/basic.js

The second issue is we decided to not add plugin examples to the main pixijs site as these would get out of date. So the redirect does fail for these examples. I will make a copy of the v7 examples under `pixijs.io/examples-v7` like before set up a better redirect to either go to the v7 examples or the pixi site depending on the example
