### ISSUE TITLE
Bug: Example applicaiton not loading

### ISSUE THREAD

**Issue by AJLProjects** [pixijs/pixijs.com#70]
### Current Behavior

![image](https://github.com/pixijs/pixijs/assets/8988872/54d01432-7ef5-4d24-8de0-acf9dd33e26d)

### Expected Behavior

A sprite should appear.

### Steps to Reproduce

Go to: https://pixijs.com/examples/sprite/basic

### Environment
FireFox

**Comment by bigtimebuddy** [comment]
I cannot reproduce this on macOS running Firefox 122. Can you please provide more details about your environment? Do any of the examples work?
